controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#below is not needed anymore since adding the route directly above the controller
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number